name: graduation_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.0.1
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  conditional_builder_null_safety: ^0.0.6
  bot_toast: ^4.0.1
  flutter_rating_bar: ^4.0.1
  loading_indicator: ^3.0.3
  flutter_statusbarcolor_ns: ^0.4.0
  jiffy: ^5.0.0
  card_swiper: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dialogs: ^0.0.7
  awesome_dialog: ^2.2.1
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  http: ^0.13.4
  intl: ^0.17.0
  snippet_coder_utils: ^1.0.12
  dropdown_button2: ^1.6.1
  flutter_custom_clippers: ^2.0.0
  uuid: ^3.0.6
  im_stepper: ^1.0.1+1
  flutter_credit_card: ^3.0.1
  stripe_payment: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/banners/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

    - family: PTSerif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/PTSerif-Bold.ttf
          weight: 700

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova-Black.otf
          weight: 900